# 1. Base Image
FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.2.rc1-910b-ubuntu22.04-py3.11

# 2. Pre-installation foundation vllm with architecture echo
RUN ARCH=$(uname -m) && \
    echo "export ARCH=$ARCH" >> ~/.bashrc && \
    echo "[LOG INFO] Current system architecture: $ARCH"

# 3. Install system dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    gcc g++ cmake libnuma-dev wget git curl jq vim build-essential \
    && rm -rf /var/lib/apt/lists/*

# 4. Install vllm
RUN ARCH=$(uname -m) && \
    echo "[LOG INFO] Detected architecture: $ARCH" && \
    if [ "$ARCH" = "x86_64" ]; then \
        echo "[LOG INFO] Entering x86_64 branch: Setting pip extra index url"; \
        pip config set global.extra-index-url "https://download.pytorch.org/whl/cpu/ https://mirrors.huaweicloud.com/ascend/repos/pypi"; \
    else \
        echo "[LOG INFO] Entering aarch64 branch: No extra pip index url set"; \
    fi && \
    git clone --depth 1 --branch v0.9.1 https://github.com/vllm-project/vllm && \
    cd vllm && \
    VLLM_TARGET_DEVICE=empty pip install -v -e . && \
    cd ..

# 5. Install vllm_ascend
RUN ARCH=$(uname -m) && \
    echo "[LOG INFO] Configuring LD_LIBRARY_PATH for $ARCH" && \
    if [ "$ARCH" = "aarch64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/8.2.RC1/aarch64-linux/devlib/linux/aarch64:$LD_LIBRARY_PATH; \
    elif [ "$ARCH" = "x86_64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/8.2.RC1/x86_64-linux/devlib/linux/x86_64/:$LD_LIBRARY_PATH; \
    fi && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    git clone --depth 1 --branch v0.9.1 https://github.com/vllm-project/vllm-ascend.git && \
    cd vllm-ascend && \
    pip install -v -e . && \
    cd ..

# 6. Install verl
RUN git clone https://github.com/volcengine/verl.git && \
    cd verl && \
    git checkout main && \
    pip install -r requirements-npu.txt && \
    pip install -e . && \
    cd ..

# 7. Install MindSpeed
RUN git clone https://gitcode.com/Ascend/MindSpeed.git && \
    cd MindSpeed && \
    git checkout f2b0977e && \
    cd .. && \
    pip install -e MindSpeed

# 8. Install Megatron-LM and configure PYTHONPATH
RUN git clone https://github.com/NVIDIA/Megatron-LM.git && \
    cd Megatron-LM && \
    git checkout core_v0.12.1 && \
    cd .. && \
    echo "export PYTHONPATH=\$PYTHONPATH:/Megatron-LM" >> ~/.bashrc

# Show pip list and clear pip cache to reduce image size
RUN pip list && pip cache purge

# Setting Default Commands
CMD ["/bin/bash"]
